apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  lables:
    app: payment
spec:
  replicas: 3
  selector:
    matchLables:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: registry.gitlab.com/sali21/ms-paiement
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  type: NodePort
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30000

